name: Pacman Contributions

on:
  schedule:
    - cron: '0 0 * * *' # daily at midnight UTC
  workflow_dispatch:

jobs:
  pacman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Pacman contributions
        uses: pacmanscripts/github-pacman@v1
        with:
          repo: ${{ github.repository }}
          output: output
